# Generated by Django 5.0.6 on 2024-07-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='')),
                ('nome', models.CharField(max_length=50)),
                ('onde_assistir', models.CharField(max_length=50)),
                ('categorias', models.CharField(choices=[('DR', 'drama'), ('C', 'comedia'), ('R', 'romance'), ('DOC', 'documentario'), ('AC', 'ação'), ('AV', 'aventura'), ('FC', 'ficção cientifica'), ('T', 'Terror')], max_length=3)),
            ],
        ),
    ]
