# Generated by Django 5.0.6 on 2024-07-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='descricao',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
