# Generated by Django 5.0.6 on 2024-07-03 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0002_filme_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.AlterField(
            model_name='filme',
            name='imagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmes.imagem'),
        ),
    ]
