# Generated by Django 5.0.6 on 2024-07-03 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0003_imagem_alter_filme_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='imagem',
        ),
    ]
