# Generated by Django 5.0.6 on 2024-07-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0004_remove_filme_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='categorias',
            field=models.CharField(max_length=50),
        ),
    ]
