# Generated by Django 5.0.6 on 2024-07-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('onde_assistir', models.CharField(max_length=50)),
                ('categoria', models.CharField(choices=[('DR', 'drama'), ('C', 'comedia'), ('R', 'romance'), ('DOC', 'documentario'), ('AC', 'ação'), ('AV', 'aventura'), ('FC', 'ficção cientifica'), ('T', 'Terror')], max_length=3)),
                ('descricao', models.TextField()),
                ('temporadas', models.IntegerField()),
                ('episodios', models.IntegerField()),
            ],
        ),
    ]
